### ISSUE TITLE
Tensor size mismatch when testing on own png

### ISSUE THREAD

**Issue by Garfield-kh** [aiff22/PyNET-PyTorch#13]
Firstly thank you for sharing this work.

I want to try test the pretrain model on my own dataset. The file extension is 'NEF'.
What I did is:
1) convert the NEF file to png through modified `dng_to_png.py`. 
2) change the `image_height` and `image_width` to `2010, 3018` , which half of original NEF image size `4020, 6032`.
3) error message: `Traceback (most recent call last):
  File "test_model.py", line 94, in <module>
    test_model()
  File "test_model.py", line 77, in test_model
    enhanced = model(raw_image.detach())
  File "/home/gongkehong/anaconda3/envs/mlenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gongkehong/anaconda3/envs/mlenv/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/gongkehong/anaconda3/envs/mlenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gongkehong/compare_git/PyNet/model.py", line 237, in forward
    output_l4, conv_t3a, conv_t3b = self.level_4(conv_l4_d1, conv_t4a, conv_t4b)
  File "/home/gongkehong/compare_git/PyNet/model.py", line 124, in level_4
    conv_l4_d2 = torch.cat([conv_l4_d1, conv_t4a], 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 250 and 251 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:83`
4) using the default setting of   `image_height` and `image_width` , this problem will not appear.
5) same error happed in TF version.

Is there any step I made mistakes?

Thank you.

**Comment by aiff22** [comment]
@Garfield-kh,

The size of the input image should be multiple of 32 due to the used down- and up-scaling layers. Changing the size from _2010 x 3018_ to  _1984 x 3008_ should fix the problem.

**Comment by Garfield-kh** [comment]
Thank you!
Yes, it works.
May I ask one more question?
When the brightness of Raw image is very high, then the resulit RGB image will be almost in white. It this because the training data is in a low exposure setting?
I failed to download the data for training thus I cannot check it myself.
The performance is quite good on low exposure RAW image.

Thank you again.

**Comment by aiff22** [comment]
Hi @Garfield-kh,

As far as I can see, you collected RAW images with a phone model different from the Huawei P20 used for training this network. Therefore, your device has another camera sensor model and optical system. While the PyNET is still able to generalize even to such hard cases, various small artifacts can be expected when applying it to raw data from other devices.

**Comment by Garfield-kh** [comment]
Thank you for the answering!
Yes, it's different  device.
What I want to try is to test on different exposure RAW using this model.

- When I try increase the exposure value of RAW, (scale up the RAW value 50% and clip on  the testing data '_test/huawei_full_resolution/1167.png_' ). It seems like the output will get some small artifacts like blue region.
- In my own different exposure RAW data, it works good for proper exposure setting, and some region of output image go blank in high exposure setting.

As the paper state '_The photos were captured in automatic mode_' in the section '_Zurich RAW to RGB dataset_', Does this means the pretrained model can only handle suitable exposure setting since the training only include proper exposure RAW image?

**Comment by Garfield-kh** [comment]
I find similar issue which in SID  (See in Dark), the author suggests to try and re-scale the raw with a proper ratio such that the model is suitable for it.
Thanks~
