### ISSUE TITLE
Problems when unzip the dataset

### ISSUE THREAD

**Issue by SSRheart** [aiff22/PyNET-PyTorch#15]
After i unzip the dataset on the linux, some images in train/huawei_raw and full_resolution/huawei_raw become the dark images. I still cannot find the reasons on the interent. Does anyone meets these issue?

**Comment by aiff22** [comment]
Hi @SSRheart,

The reason is that the input data is 10-bit images, and they cannot be displayed properly in any standard image viewer. Please refer to [this](https://github.com/aiff22/PyNET-PyTorch/issues/6) and [this](https://github.com/aiff22/PyNET/issues/2) issue for more details.
