### ISSUE TITLE
Could I use it without GPU?(only forward inference)

### ISSUE THREAD

**Issue by antenna-before** [aiff22/PyNET-PyTorch#3]
Sad to say that I don't have a GPU~

**Comment by aiff22** [comment]
Hi @tureliuyaohua,

Yes, you can run inference on your CPU by setting ``use_gpu`` option to false:

```bash
python test_model.py level=0 orig=true use_gpu=false
```

**Comment by antenna-before** [comment]
Thank you very much, I have a try~
