### ISSUE TITLE
how to test the model on my own dataset with pretrained model

### ISSUE THREAD

**Issue by ChaoyiXie** [aiff22/PyNET-PyTorch#4]
my raw dataset is dng format ,so I want to know how can I input one dng fromat image ,then output the enhance image by pretrained model

**Comment by Jam-G** [comment]
@ChaoyiXie  there is a python package named rawpy can parse raw files like 'dng',  you can get it by:
`pip install rawpy`

And in this repo, there is a file named `dng_to_png.py`, you can use it to convert dng files to png files. But one thing you should noticed is that the raw file should be RGGB Bayer pattern， or  BGGR pattern（then you should de-comment the line `raw_image = np.rot90(raw_image, k=2)` which could change RGGB pattern to BGGR, vice versa）when use the dng_to_png.py.

**Comment by datduong** [comment]
Hi, how do I run the model when I have jpeg inputs? Would I need to convert it into height x width x channel inputs?

**Comment by pedroHuang123** [comment]
I can not download the pre-trained model, can you shared it to me , thanks
