### ISSUE TITLE
FileNotFoundError: No such file: '.../PyNET-PyTorch/raw_images/test/huawei_full_resolution/0.png'

### ISSUE THREAD

**Issue by XGBoost** [aiff22/PyNET-PyTorch#5]
It seems that, following codes is used to save visual results for several test images.

'''

                generator.eval()
                with torch.no_grad():
                    visual_iter = iter(visual_loader)
                    for j in range(len(visual_loader)):

                        torch.cuda.empty_cache()

                        raw_image = next(visual_iter)
                        raw_image = raw_image.to(device, non_blocking=True)

                        enhanced = generator(raw_image.detach())
                        enhanced = np.asarray(to_image(torch.squeeze(enhanced.detach().cpu())))

                        imageio.imwrite("results/pynet_img_" + str(j) + "_level_" + str(level) + "_epoch_" +
                                        str(epoch) + ".jpg", enhanced)
'''
However, images in folder in 'raw_images/test/huawei_full_resolution' do not have index '0'. 
And the image size is not 448*448.

**Comment by aiff22** [comment]
Hi @XGBoost,

Thanks a lot for informing about the issue. [This commit](https://github.com/aiff22/PyNET-PyTorch/commit/4310e7a5fbc94587ab454ebdebd8abccad92c02f) should fix the problem.

> And the image size is not 448*448.

In this repository, full-resolution images are used for visual inspection of the results.

**Comment by XGBoost** [comment]
@aiff22 Thank you very much~
