### ISSUE TITLE
Level 5 didn't use skip connection

### ISSUE THREAD

**Issue by poveryang** [aiff22/PyNET-PyTorch#8]
@aiff22 Hi:
I checked the source code (PyNET-PyTorch) and I found that skip connetion is not used in Level 5,but the connection represented in the paper's illustration.

**Comment by Jam-G** [comment]
@pover-yang See also [this Issue](https://github.com/aiff22/PyNET/issues/5)

**Comment by poveryang** [comment]
> @pover-yang See also [this Issue](https://github.com/aiff22/PyNET/issues/5)

Thank you!
